applications:
  - ansible
  - awscli
  - dos2unix
  - git
  - httpie
  - jq
  - nmap
  - tmux
  - unrar
  - watch
  - xz

applications_cask:
  - docker
  - iterm2
  - ngrok
  - vagrant
  - virtualbox
  - wireshark
